import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Providers from "@/providers/Providers";
import Navbar from "@/components/ui/Navbar";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next App with PostgreSQL with Prisma + NextAuth",
  description: "Generated by create next app, Includes prisma, postgreSQL with authentication!",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning>
      <body className={inter.className} suppressHydrationWarning>
        <Providers>
          <main className="max-w-screen flex h-screen dark:text-white text-gray-800 bg-white dark:bg-primary-black">
            <Navbar />
            <div className="flex-1 pt-16 p-6">
              {children}
            </div>
          </main>
          <Toaster richColors position="bottom-right" />
        </Providers>
      </body>
    </html >
  );
}
